name: Badminton Booking

on:
  workflow_dispatch:

jobs:
  runs-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run : |
          pip install -r requirements.txt
      
      - name: Run script
        run : |
          python main.py